// This file was generated by CMake

#pragma once

namespace xlang::strings {

extern char const constexpr_definitions[110];

extern char const constexpr_end_definitions[36];

extern char const deprecated_header_end[197];

extern char const deprecated_header_start[1132];

extern char const enum_class[97];

extern char const file_header[651];

extern char const include_guard_end[41];

extern char const include_guard_start[84];

extern char const ns_prefix_always[39];

extern char const ns_prefix_definitions[430];

extern char const ns_prefix_never[38];

extern char const ns_prefix_optional[136];

extern char const optional_ns_prefix_definitions[960];

extern char const optional_ns_prefix_end_definitions[177];

}

